name: 打包并发布 mini_fonts

on:
  push:
    branches: [ main ]

jobs:
  build_and_release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: 打包字体
        run: |
          mkdir -p dist
          zip -r dist/mini_fonts.zip mini_fonts

      - name: 创建发布版本
        id: create_release
        uses: actions/create-release@v3
        with:
          tag_name: ${{ github.event.release.tag_name }}
          release_name: ${{ github.event.release.tag_name }}
          body: ${{ github.event.release.body }}

      - name: 上传打包字体
        uses: actions/upload-release-asset@v3
        with:
          release_id: ${{ steps.create_release.outputs.id }}
          asset_name: mini_fonts.zip
          asset_path: dist/mini_fonts.zip
