name: Bump version and Release

on:
  workflow_dispatch:
  push:
    tags:
      - '*'


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: List current directory
        run: ls -la
          
      - name: Build
        run: |
          tar -czvf mini_fonts.tar.gz mini_fonts
          ls -la mini_fonts.tar.gz  # 检查生成的压缩文件
          
      - name: List files in mini_fonts
        run: ls -la mini_fonts
      
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: mini_fonts.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
