name: Bump version and Release

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag Name'  # 添加一个标签名输入字段
        required: true
        default: 'v1.0.0'  # 可以提供一个默认值


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: List current directory
        run: ls -la
          
      - name: Build
        run: |
          cd mini_fonts && tar -czvf ../mini_fonts.tar.gz *
          ls -la ../mini_fonts.tar.gz  # 检查生成的压缩文件

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: ../mini_fonts.tar.gz  # 调整文件路径
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false
