name: Bump version and Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'  # 确保获取全部 git 历史

      - name: Compress mini_fonts folder
        run: tar -czvf mini_fonts.tar.gz mini_fonts

      - name: Create Release
        uses: softprops/action-gh-release@v2.0.5
        with:
          files: mini_fonts.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
