name: Bump version and Release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: List current directory
        run: ls -la
          
      - name: Build
        run: |
          cd mini_fonts && tar -czvf ../mini_fonts.tar.gz *
          ls -la ../mini_fonts.tar.gz  # 检查生成的压缩文件

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          files: ../mini_fonts.tar.gz  # 调整文件路径
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false
